import esbuild from "esbuild";
import fs from "fs";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
QReader — Read with Questions
*/
`;

const prod = process.argv[2] === "production";

// Keep the worker and all PDF decoding resources inside main.js.
const pdfAssetsPlugin = {
  name: "offline-pdf-assets",
  setup(build) {
    build.onLoad({ filter: /pdf\.worker(\.min)?\.mjs$/ }, async (args) => ({
      contents: `export default ${JSON.stringify(await fs.promises.readFile(args.path, "utf8"))};`,
      loader: "js",
    }));
    build.onResolve({ filter: /^qreader:pdf-assets$/ }, () => ({
      path: "pdf-assets",
      namespace: "qreader",
    }));
    build.onLoad({ filter: /.*/, namespace: "qreader" }, async () => {
      const assets = {};
      for (const dir of ["standard_fonts", "cmaps", "wasm"]) {
        const root = `node_modules/pdfjs-dist/${dir}`;
        for (const file of await fs.promises.readdir(root)) {
          if (!/\.(pfb|ttf|bcmap|wasm)$/.test(file)) continue;
          assets[`${dir}/${file}`] = (await fs.promises.readFile(`${root}/${file}`)).toString("base64");
        }
      }
      return { contents: `export default ${JSON.stringify(assets)};`, loader: "js" };
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  platform: "browser",
  alias: {
    "jszip/dist/jszip": "jszip/lib/index.js",
    stream: "stream-browserify",
    buffer: "buffer/",
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  outfile: "main.js",
  sourcemap: prod ? false : "inline",
  minify: prod,
  loader: { ".pfb": "base64", ".ttf": "base64" },
  plugins: [pdfAssetsPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
