import assert from 'node:assert/strict';
import { build } from 'esbuild';
process.on('uncaughtException', error => { console.error(error.message); console.error(error.stack?.split('\n').filter(line => !line.includes('data:text/')).join('\n')); process.exitCode = 1; });

// Exercise persisted versions and failure paths independently of Obsidian UI.
const bundle = await build({stdin:{contents:`export * from './src/core/thought-data'; export * from './src/core/thinking'; export * from './src/core/json-store'; export * from './src/core/md-notes'; export * from './src/ai/thought-relations';`,resolveDir:process.cwd()},bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'host-test',setup(b){
  b.onResolve({filter:/^(obsidian|epubjs)$/},args=>({path:args.path,namespace:'test'}));
  b.onLoad({filter:/.*/,namespace:'test'},args=>({contents:args.path==='obsidian'?'export const requestUrl = async options => globalThis.qrRequest(options);':'export class EpubCFI { compare(){ return 0; } }',loader:'js'}));
}}]});
const m = await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const at='2026-10-01T01:00:00Z';
const reading={version:1,book:{title:'逻辑与判断',author:'读者',format:'epub',fileName:'book.epub'},progress:{chapterId:'c1',percent:0,lastReadAt:at},chapters:{c1:{title:'第一章',index:0,questionVersions:[],answers:[],reviews:[]}},annotations:[{id:'a1',chapterId:'c1',createdAt:at,kind:'annotation',text:'Evidence can challenge our beliefs.',note:'证据可能修正判断',sortKey:1}],importedAt:at};
const entry={id:'book1',dir:'阅读库/book1',reading};
const old=m.traceSources([entry])[0];
assert.equal(old.ref.revisionId,'legacy'); assert.equal(old.baseline,true);
const record=reading.annotations[0];
m.appendAnnotationRevision(record,{...record}); assert.equal(record.history,undefined,'viewing or unchanged edits must not fabricate revisions');
const before={...record}; record.note='新的证据可以支持或修正判断'; m.appendAnnotationRevision(record,before);
assert.equal(record.history.length,2); assert.equal(record.history[0].note,'证据可能修正判断'); assert.equal(record.history[0].id,'legacy');
const latest=m.traceSources([entry],true)[0]; assert.notEqual(latest.key,old.key);
assert.equal(m.traceSources([entry]).find(s=>s.key===old.key).note,old.note,'a saved reference must retain its exact earlier text');
const colorBefore={...record};record.color='blue';m.appendAnnotationRevision(record,colorBefore);assert.equal(record.history.length,2,'color changes are not changes of thought');
m.validateReading(structuredClone(reading));
for(const change of [r=>r.annotations[0].history[1].note='mismatch',r=>r.annotations[0].history[1].id='legacy',r=>r.annotations[0].history[0].at='invalid',r=>r.annotations[0].history=[]]) {const bad=structuredClone(reading);change(bad);assert.throws(()=>m.validateReading(bad));}
reading.bookNotes=[{id:'bn1',text:'跨书比较证据与判断',createdAt:at,history:[{id:'bnrev',at,note:'跨书比较证据与判断'}]}];
m.validateReading(reading);assert.ok(m.renderAnnotationsMd(reading).includes('跨书比较证据与判断'));assert.ok(m.renderAnnotationsMd(reading).includes('当时的想法'));
const candidate=(id,note,quote='')=>{const ref={bookId:id,kind:'bookNote',id,revisionId:'r1'};return {ref,key:m.traceKey(ref),bookTitle:id,chapterTitle:'',quote,note,at,baseline:false};};
const zh=candidate('book2','证据如何修正判断');const en=candidate('book3','Evidence changes beliefs and supports judgment');
assert.ok(m.relatedCandidates(latest,[old,latest,zh]).some(s=>s.key===zh.key));
assert.ok(!m.relatedCandidates(latest,[old,latest,zh]).some(s=>s.ref.bookId==='book1'));
assert.equal(m.relatedCandidates(candidate('source','completely unrelated spaceship'),[zh]).length,0);
assert.equal(m.relatedCandidates(candidate('source','Evidence changes beliefs'),[en])[0].key,en.key);
assert.equal(m.relatedCandidates(latest,[candidate('ai-only','',latest.note)]).length,0,'AI explanation and highlights alone must not become personal thoughts');
assert.ok(m.relatedCandidates(latest,Array.from({length:30},(_,i)=>candidate('x'+i,'证据修正判断'))).length<=10);
const response={suggestions:[{targetId:'n1',relation:'refine',reason:'新笔记补充了证据的作用',title:'证据与判断'}]};
assert.equal(m.parseSuggestions(JSON.stringify(response),[zh])[0].targetKey,zh.key);
for(const bad of [{suggestions:[{...response.suggestions[0],targetId:'n9'}]},{suggestions:[...response.suggestions,...response.suggestions]},{suggestions:[{...response.suggestions[0],relation:'confidence'}]},{suggestions:[{...response.suggestions[0],score:0.9}]},{suggestions:[],judgment:'AI替你判断'},{suggestions:Array(4).fill(response.suggestions[0])}])assert.throws(()=>m.parseSuggestions(JSON.stringify(bad),[zh]));
assert.deepEqual(m.parseSuggestions('{"suggestions":[]}',[zh]),[]);
assert.throws(()=>m.validateRef({bookId:'b',kind:'file',id:'../secret',revisionId:'r'}));
let requests=[];
globalThis.qrRequest=async options=>{requests.push(options);return {status:200,text:JSON.stringify({choices:[{message:{content:JSON.stringify(response)}}]})};};
const config={baseUrl:'https://example.test/v1',apiKey:'fixture-only',model:'fixture-model'};
await m.suggestRelations(config,latest,[zh],'zh-CN');await m.suggestRelations(config,latest,[zh],'en');
assert.equal(requests.length,2);const payloads=requests.map(r=>JSON.parse(r.body));
assert.ok(payloads[0].messages[0].content.includes('简体中文'));assert.ok(payloads[1].messages[0].content.includes('English'));
assert.equal(JSON.parse(payloads[0].messages[1].content).candidates.length,1);
await m.suggestRelations(config,latest,[],'en');assert.equal(requests.length,2,'no candidates must make no API call');
await m.suggestRelations(config,candidate('source','证据'.repeat(1000),'原文'.repeat(1000)),Array.from({length:20},(_,i)=>candidate('candidate'+i,'笔记'.repeat(1000),'引用'.repeat(1000))),'en');
const bounded=JSON.parse(JSON.parse(requests.at(-1).body).messages[1].content);assert.equal(bounded.candidates.length,10);assert.equal(bounded.source.readerNote.length,700);assert.equal(bounded.source.quote.length,500);assert.ok(bounded.candidates.every(c=>c.readerNote.length===700&&c.quote.length===500));
const files=new Map();let failWrite=false,root='阅读库';
const fs={queueScope:{},exists:async p=>files.has(p),read:async p=>{if(!files.has(p))throw Error('missing');return files.get(p);},write:async(p,v)=>{if(failWrite&&p.endsWith('thinking.json')){failWrite=false;throw Error('disk-full');}files.set(p,v);},remove:async p=>files.delete(p),mkdir:async()=>{}};
let sources=[old,latest,zh];let notifications=0;
const manager=new m.ThinkingManager(fs,async()=>root,ref=>sources.find(s=>s.key===m.traceKey(ref)),()=>notifications++);
assert.deepEqual(await manager.load(),{version:1,threads:[]});assert.equal(files.size,0,'opening notes must not persist or call AI');
const items=[{ref:old.ref,relation:'related',reason:'我确认的关联',addedAt:at},{ref:zh.ref,relation:'refine',reason:'跨书补充',addedAt:at}];
const id=await manager.saveThread(undefined,'证据与判断','我的当前判断','还想找反例',items);
const path='阅读库/.qreader/thinking.json'; const fileBefore=files.get(path);
assert.ok(!fileBefore.includes('Evidence can challenge'),'thread files must reference sources, not duplicate quotations');
const thread=(await manager.load()).threads[0];
await manager.addItems(id,items);assert.equal(thread.items.length,2,'confirmed sources must deduplicate by exact revision');
failWrite=true;await assert.rejects(()=>manager.saveThread(id,'更改后','不能保存的判断',''),/disk-full/);assert.equal(thread.judgment,'我的当前判断');assert.equal((await manager.load()).threads[0],thread,'rollback must keep live references');
await Promise.all([manager.saveThread(id,'证据与判断','我自己的判断','问题'),manager.addItems(id,[{ref:latest.ref,relation:'support',reason:'再次阅读',addedAt:at}])]);
assert.equal(thread.items.length,3);assert.equal(thread.judgment,'我自己的判断');
const export1=await manager.exportMarkdown(thread,sources);const export2=await manager.exportMarkdown(thread,sources);assert.notEqual(export1,export2);
assert.ok(files.get(export1).includes('证据可能修正判断'));assert.ok(files.get(export1).includes('obsidian://qreader?'));assert.ok(files.get(export1).includes('导出快照'));
sources=sources.filter(s=>s.key!==old.key);const deleted=m.renderThoughtMarkdown(thread,sources);assert.ok(deleted.includes('来源已删除或不可用'));assert.ok(!deleted.includes('证据可能修正判断'),'deleted sources must not leak a duplicated old note');
assert.ok(files.get(export1).includes('证据可能修正判断'),'explicit Markdown exports are independent snapshots');
const englishSnapshot=m.renderThoughtMarkdown(thread,sources,'en','My Vault');assert.ok(englishSnapshot.includes('My current view'));assert.ok(englishSnapshot.includes('vault=My+Vault'));assert.ok(!englishSnapshot.includes('## 我目前怎么看'));
await manager.removeItem(id,latest.ref);assert.equal(thread.items.length,2);
await manager.deleteThread(id);assert.equal((await manager.load()).threads.length,0);assert.equal(record.history.length,2,'thread deletion must leave source notes intact');
root='另一阅读库';assert.equal((await manager.load()).threads.length,0);await manager.saveThread(undefined,'另一条线','','',[]);assert.ok(files.has('另一阅读库/.qreader/thinking.json'));
root='阅读库';const external='{"version":1,"threads":[]} ';files.set(path,external);await assert.rejects(()=>manager.saveThread(undefined,'外部修改后','',''),/thinking.json.*不一致/);assert.equal(files.get(path),external,'external changes must never be overwritten');
await manager.load(true);await manager.saveThread(undefined,'重载后','','');
const backup=files.get(path+'.recovery');assert.ok(backup);files.set(path,'{broken');await assert.rejects(()=>manager.load(true),/损坏/);assert.equal(files.get(path),'{broken');await assert.rejects(()=>manager.saveThread(undefined,'损坏时','',''),/损坏/);
await manager.restoreBackup();assert.equal(files.get(path),backup);assert.ok([...files.keys()].some(p=>p.endsWith('.corrupt')),'explicit recovery must preserve the damaged original');
assert.ok(notifications>0);assert.equal(requests.length,3,'persistence, browsing, exporting and deleting must never invoke AI');
root='并发阅读库';const first=new m.ThinkingManager(fs,async()=>root,()=>undefined,()=>{}),second=new m.ThinkingManager(fs,async()=>root,()=>undefined,()=>{});
await Promise.all([first.load(),second.load()]);await first.saveThread(undefined,'先保存的想法','','');await assert.rejects(()=>second.saveThread(undefined,'旧页面的想法','',''),/thinking.json.*不一致/);assert.equal((await second.load(true)).threads[0].title,'先保存的想法');
console.log('Thinking: exact revisions, CJK/English retrieval, constrained bilingual AI, explicit connections, rollback, deletion, isolated roots, snapshots and damaged-file recovery passed.');
